[package]
name = "decancer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-normalization = "0.1.23"
regex = "1.10.4"
unidecode = "0.3.0"
